# System and Logging
CONFIG_LOG=y
CONFIG_LOG_BACKEND_UART=y
CONFIG_LOG_BACKEND_SWO=y

# Support for float values in printf/logging
CONFIG_CBPRINTF_FP_SUPPORT=y

# Hardware Subsystems
CONFIG_I2C=y
CONFIG_SENSOR=y
CONFIG_GPIO=y

# Sensor Drivers (Phase 1)
CONFIG_MAX30101=y
CONFIG_MAX30101_TRIGGER_GLOBAL_THREAD=y
