# System and Logging
CONFIG_LOG=y
CONFIG_LOG_BACKEND_UART=y
CONFIG_LOG_BACKEND_SWO=y

# Support for float values in printf/logging
CONFIG_CBPRINTF_FP_SUPPORT=y

# C++ Support for Arduino Libraries
CONFIG_CPP=y
CONFIG_STD_CPP17=y
CONFIG_REQUIRES_FULL_LIBC=y

# Hardware Subsystems
CONFIG_I2C=y
CONFIG_SENSOR=y
CONFIG_GPIO=y

# Disable Zephyr's internal MAX30101 driver so we can use EmotiBit's C++ library
# CONFIG_MAX30101=y
# CONFIG_MAX30101_TRIGGER_GLOBAL_THREAD=y

# TCA9548A MUX Initialization Priorities (must be > I2C_INIT_PRIORITY)
CONFIG_I2C_TCA954X_ROOT_INIT_PRIO=60
CONFIG_I2C_TCA954X_CHANNEL_INIT_PRIO=70
